apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-build-box
  namespace: lae-development
  labels:
    app: android-build-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android-build-box
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: android-build-box
      annotations:
        botkube.io/channel: "university-k8s"
    spec:
      serviceAccountName: azure-workload-identity-service-account
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: android-build-box
          image: businessschool.azurecr.io/business-school/android-build-box:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              #if less - it may fail on the fresh start
              memory: 4992Mi  # ~4.875 Gi
            requests:
              cpu: 500m
              memory: 1536Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 10
          volumeMounts:
            - name: secrets-store-inline # mount the keyvault secret as volume inside the container
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: android-build-box-ssh-keys
              mountPath: "/home/docker/.ssh"
              readOnly: true
          env:
            - name: HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: android-build-box-secret
                  key: HOST_NAME
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: android-build-box-secret
                  key: SLACK-TOKEN
            - name: SPOT_LOCAL_IDENTITY_MAGICK
              valueFrom:
                secretKeyRef:
                  name: android-build-box-secret
                  key: SPOT_LOCAL_IDENTITY_MAGICK
            - name: SPOT_LOCAL_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: android-build-box-secret
                  key: SPOT_LOCAL_TOKEN_SALT
            - name: JFROG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: android-build-box-secret
                  key: JFROG_USERNAME
            - name: JFROG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: android-build-box-secret
                  key: JFROG_PASSWORD
      imagePullSecrets:
        - name: businessschool-azurecr-io-regsecret
      volumes:
        - name: secrets-store-inline # keyvault csi secret volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keyvault-android-build-box-lae-development # metadata.name in secret-provider-class.yaml
              secretProviderClassNamespace: lae-development
        - name: android-build-box-ssh-keys
          secret:
            secretName: android-build-box-ssh-keys
            defaultMode: 0600
