---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secret-code-lae-development
  namespace: lae-development
spec:
  secretObjects:
    - data:
        - key: ANDROID-APP-BOX-SLACK-TOKEN
          objectName: ANDROID-APP-BOX-SLACK-TOKEN
      secretName: android-app-box-secret
      type: Opaque
    - data:
        - key: ANDROID-APP-BOX-SSH-PRIVATE-KEY
          objectName: ANDROID-APP-BOX-SSH-PRIVATE-KEY
        - key: ANDROID-APP-BOX-SSH-PUBLIC-KEY
          objectName: ANDROID-APP-BOX-SSH-PUBLIC-KEY
      secretName: ssh-keys-secret
      type: kubernetes.io/ssh-auth
  provider: azure
  parameters:
    keyvaultName: k8s-lae-development
    objects: |
      array:
        - |
          objectName: ANDROID-APP-BOX-SSH-PRIVATE-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-APP-BOX-SSH-PUBLIC-KEY
          objectType: secret
          objectVersion: ""
