apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-android-build-box-lae-development
  namespace: lae-development
spec:
  provider: azure
  secretObjects:
    - secretName: android-build-box-secret
      type: Opaque
      data:
        - key: SLACK-TOKEN
          objectName: ANDROID-BUILD-BOX-SLACK-TOKEN
        - key: HOST_NAME
          objectName: ANDROID-BUILD-BOX-HOST-NAME
        - key: SPOT_LOCAL_TOKEN_SALT
          objectName: ANDROID-BUILD-BOX-SPOT-LOCAL-TOKEN-SALT
        - key: SPOT_LOCAL_IDENTITY_MAGICK
          objectName: ANDROID-BUILD-BOX-SPOT-LOCAL-IDENTITY-MAGICK
        - key: JFROG_USERNAME
          objectName: ANDROID-BUILD-BOX-JFROG-USERNAME
        - key: JFROG_PASSWORD
          objectName: ANDROID-BUILD-BOX-JFROG-PASSWORD
    - secretName: android-build-box-ssh-keys
      type: Opaque
      data:
        - key: id_rsa
          objectName: ANDROID-BUILD-BOX-SSH-PRIVATE-KEY
        - key: id_rsa.pub
          objectName: ANDROID-BUILD-BOX-SSH-PUBLIC-KEY
  parameters:
    keyvaultName: k8s-lae-development
    objects: |
      array:
        - |
          objectName: ANDROID-BUILD-BOX-HOST-NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-SLACK-TOKEN
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-SSH-PUBLIC-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-SSH-PRIVATE-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-SPOT-LOCAL-TOKEN-SALT
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-SPOT-LOCAL-IDENTITY-MAGICK
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-JFROG-USERNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: ANDROID-BUILD-BOX-JFROG-PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: "01467f4f-db36-41a3-a52d-f91dad816bab"
    clientID: "745e437d-a575-4a8e-a04b-42ff33ad4133"
