apiVersion: v1
kind: Service
metadata:
  name: android-build-box
  namespace: lae-development
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: android-build-box
