apiVersion: v1
kind: Service
metadata:
  name: university-android-app-box
  namespace: lae-development
spec:
  ports:
  - port: 80
    targetPort: 8282
    protocol: TCP
  selector:
    app: university-android-app-box
